---
title: "get_scdev"
author: "ks"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in the deviances Kelly computed for single-cell colon data.

```{r read-colon, warning=FALSE}
#fn <-  c("~kims/Google Drive/My Drive/MyFolder/People/Darryl Shibata/plasticity/20230123/forKIMnormaltumordeviancegraph1-23.xlsx")
fn <-  c("~kims/Google Drive/My Drive/Data/hpc-archive/annotations/forKIMnormaltumordeviancegraph1-23.xlsx")

# grab row 2 data as column names for columns: 1-4, 27
scdev <- readxl::read_xlsx(fn,sheet = "gene_normal",col_names = TRUE, skip=1)
scdev <- scdev[!is.na(scdev$`log2dev+1`),]
dim(scdev)

scdev <- cbind.data.frame(genesymbol = scdev$gene,
                          depmap_esstl = ifelse(!is.na(scdev$`common essential`),
                                   "essential","inducible"),
                          colon_ldev = scdev$`log2dev+1`
                  )

table(scdev$depmap_esstl)
```

Add some jitter to the values so we can plot the values near 0 and they are not all overlapping.

```{r jitter}
set.seed(1234)
scdev$jcolon_ldev <-jitter(scdev$colon_ldev,amount=0.5)
head(scdev)
```


How do I map gene symbols to entrez gene ids
```{r}
library(AnnotationDbi)
library(org.Hs.eg.db) 

# Map gene symbols to entrez gene IDs
gene_symbol_map <- AnnotationDbi::select(org.Hs.eg.db, 
                          keys = as.character(scdev$genesymbol), 
                          column = "ENTREZID", keytype = "SYMBOL", 
                     multiVals = "first")
# Add gene IDs to the sc deviance data.
scdev$gene_ids <- gene_symbol_map$ENTREZID[match(as.character(scdev$genesymbol),
               gene_symbol_map$SYMBOL)]
# is this last step unnecessary?
save(scdev,file = "data/scdev.rda")
```

I lose 4400 genes trying to map the symbol to Entrez gene id.
