---
title: "JASPAR 2022"
author: "ks"
date: "2024-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r install}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("JASPAR2024", update = FALSE)
BiocManager::install("AnnotationHub", update = FALSE) 
BiocManager::install("plyranges", update = FALSE)
```

## CTCF is in AnnotationHub

```{r get-ctcf}
suppressMessages(library(AnnotationHub))
ah <- AnnotationHub()
query_data <- subset(ah, preparerclass == "CTCF")
# Explore the AnnotationHub object
query_data
query_data$dataprovider %>% table()
```


```{r hg38-jaspar2022}
subset(query_data, species == "Homo sapiens" & 
                   genome == "hg38" & 
                   dataprovider == "JASPAR 2022")
```


```{r ctcf-allmotifs}
CTCF_hg38_all <- query_data[["AH104727"]]
CTCF_hg38_all
```

```{r ctcf-mostpopmotif}
CTCF_hg38_ma0139.1 <- query_data[["AH104729"]]
CTCF_hg38_ma0139.1
```

```{r}
saveRDS(CTCF_hg38_all,file="data/ctcf.all.rds")
```

```{r}
saveRDS(CTCF_hg38_ma0139.1,file="data/ctcf.ma0139.1.rds")
```
